DROP DATABASE IF EXISTS bd_INF3005;

CREATE DATABASE bd_INF3005 CHARACTER SET 'utf8';

CREATE USER 'inf3005'@'localhost' IDENTIFIED BY 'inf3005';

GRANT ALL
 ON bd_INF3005.*
 TO 'inf3005'@'localhost';

 
CREATE TABLE CATEGORIE(
    ID_CATEGO   SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOM_CATEGO  VARCHAR(50)  NOT NULL,
    MOT_CLE     VARCHAR(50) NOT NULL,
    PRIMARY KEY (NOM_CATEGO,MOT_CLE),
    UNIQUE (ID_CATEGO)
    )ENGINE = INNODB;

CREATE TABLE ADRESSE(
    
    PAYS VARCHAR (30),
    PROVINCE VARCHAR(30),
    VILLE VARCHAR(50),
    MUNICI   VARCHAR(50),
    RUE VARCHAR(50),
    NUM_CIVIC VARCHAR(10),
    CODE_POS VARCHAR(10) NOT NULL,
    ID_ADR   SMALLINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (CODE_POS),
    UNIQUE (ID_ADR)
)
ENGINE = INNODB;
 
CREATE TABLE USERS(
    NOM       VARCHAR(30) NOT NULL,
    PRENOM    VARCHAR(30),
    TEL       VARCHAR(50),
    COURRIEL  VARCHAR(100) NOT NULL,
    PHOTO     VARCHAR(100),
    PWD       VARCHAR(50) NOT NULL,
    ROLE      VARCHAR(50) DEFAULT 'user' NOT NULL,
    ID_ADR    SMALLINT NOT NULL,
            PRIMARY KEY (COURRIEL),
    CONSTRAINT FK_ID_ADR
    FOREIGN KEY (ID_ADR)
    REFERENCES ADRESSE(ID_ADR)    
)ENGINE = INNODB;

CREATE TABLE PREFERENCE(
    COURRIEL    VARCHAR(100) NOT NULL,
    NOM_CATEGO  VARCHAR(50)  NOT NULL,
    MOT_CLE     VARCHAR(50)  NOT NULL,
    PRIMARY KEY (COURRIEL,NOM_CATEGO,MOT_CLE),
    
    CONSTRAINT FK_ID_CATEGO
    FOREIGN KEY (NOM_CATEGO,MOT_CLE)
    REFERENCES CATEGORIE(NOM_CATEGO,MOT_CLE)
    ON UPDATE CASCADE
    ON DELETE CASCADE, 
    
    CONSTRAINT FK_ID_USER
    FOREIGN KEY (COURRIEL)
    REFERENCES USERS(COURRIEL)  
    ON UPDATE CASCADE
    ON DELETE CASCADE
)ENGINE = INNODB;

CREATE TABLE STATISTIQUE(
    COURRIEL     VARCHAR(100) NOT NULL,
    NBRE_CON  SMALLINT DEFAULT 0,
    PRIMARY KEY (COURRIEL),
    
    CONSTRAINT FK_ID_USER
    FOREIGN KEY (COURRIEL)
    REFERENCES USERS(COURRIEL) 
)ENGINE = INNODB;

INSERT INTO CATEGORIE (ID_CATEGO , NOM_CATEGO, MOT_CLE) VALUES (1,'camer', 'CE');
INSERT INTO ADRESSE (PAYS, PROVINCE, VILLE, MUNICI,RUE,CODE_POS,ID_ADR) VALUES ('camer', 'CE', 'yde','II','messa','000',1);
INSERT INTO USERS (NOM, PRENOM, TEL, COURRIEL,PHOTO,PWD,ROLE,ID_ADR) VALUES ('kaiz','sozer','123852','coyote@mail.ame',NULL,'bipbip', 'user', 1);
INSERT INTO USERS (NOM, PRENOM, TEL, COURRIEL,PHOTO,PWD,ROLE,ID_ADR) VALUES ('admin','admin','123852','admin@mail.ame',NULL,'admin', 'admin', 1);
INSERT INTO PREFERENCE (COURRIEL, NOM_CATEGO, MOT_CLE) VALUES ('coyote@mail.ame', 'camer', 'CE');


